# -*- coding: utf-8 -*-
"""EvePark_Heating_&_Cooling_Pred_by_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15LqWkxVahLUiijDzoOkPbaO__Caq6kVm
"""

from google.colab import drive
from google.colab import files
import pandas as pd

# Load Eve Park_dataset
df = pd.read_excel('Eve Park_dataset.xlsx')

# Load the Nasa Weather Retscreen dataset
weather_df = pd.read_excel('Weather Nasa data_Retscreen.xlsx')

# Merge the two datasets based on the 'DateTime' column
df = pd.merge(df, weather_df, left_on='DateTime', right_on='Begin', how='left')

# Display the merged dataset
print(df.head())

import numpy as np

#calculate ω

df['Saturation Vapor Pressure - Pg (kPa)'] = 6.112 * np.exp(
    17.62 * df['Air temperature - average (°C)'] /
    (df['Air temperature - average (°C)'] + 243.12)
)

df['Water Vapor Partial Pressure - Pv (kPa)'] = df['Relative humidity (%)'] * df['Saturation Vapor Pressure - Pg (kPa)']

df['ω (kg H2O/kg dry air)'] = 0.622 * df['Water Vapor Partial Pressure - Pv (kPa)'] / (
    df['Atmospheric pressure (kPa)'] - df['Water Vapor Partial Pressure - Pv (kPa)']
)

df.head()

# Convert the 'DateTime' column to datetime format
df['DateTime'] = pd.to_datetime(df['DateTime'])

# Extract hour, day, and month
df['hour'] = df['DateTime'].dt.hour
df['day'] = df['DateTime'].dt.day
df['month'] = df['DateTime'].dt.month
df['season'] = df['month'].apply(lambda x: 'Winter' if x in [12, 1, 2,3] else ('Spring' if x in [4, 5] else 'Other'))

# Extract day of the week (0 = Monday, 6 = Sunday)
df['day_of_week'] = df['DateTime'].dt.dayofweek

# Show the updated dataframe
print(df[['DateTime', 'hour', 'day', 'month', 'day_of_week','season']].head())

# Check for missing values in each column
missing_values = df.isnull().sum()

# Display columns with missing values only
missing_columns = missing_values[missing_values > 0]
print(missing_columns)

# Specify the columns to handle missing values
columns_to_fill = ['Furnace (kWhs)', 'Water Heater (kWhs)', 'HRV (kWhs)', 'Air Conditioner (kWhs)',
                   'Building number','no of bedrom','Total energy consumption-All appliances(kWhs)',
                   'Non HVAC (kWh)','Non HVAC +1h (kWh)','Non HVAC +2h (kWh)']

# Fill forward missing values
df[columns_to_fill] = df[columns_to_fill].fillna(method='ffill')

# Replace any remaining missing values with 0
df[columns_to_fill] = df[columns_to_fill].fillna(0)

# Check if there are still any missing values in the specified columns
missing_values = df[columns_to_fill].isnull().sum()
print("Missing values after fill forward and replacing with 0:")
print(missing_values)

# Heating Load Calculation
df['Heating Load (kWhs)'] = df['Furnace (kWhs)'] + df['HRV (kWhs)'] + df['Water Heater (kWhs)']
df.loc[df['season'] == 'Winter', 'Heating Load (kWhs)'] += df['Air Conditioner (kWhs)']

# Cooling Load Calculation
df['Cooling Load (kWhs)'] = 0.0  # Initialize as 0
df.loc[df['season'] == 'Spring', 'Cooling Load (kWhs)'] += df['Air Conditioner (kWhs)']

# Plot Total consumption from All appliances by month
import matplotlib.pyplot as plt

# Extract the month and year for grouping
df['month'] = df['DateTime'].dt.month
df['year'] = df['DateTime'].dt.year

# Filter buildings data
buildings = [301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312]
df_filtered = df[(df['Building number'].isin(buildings)) & (df['DateTime'] >= '2021-12-01') & (df['DateTime'] <= '2022-05-31')]

# Group by month and building number to calculate monthly total energy consumption
monthly_consumption = df_filtered.groupby([df_filtered['DateTime'].dt.to_period('M'), 'Building number'])['Total energy consumption-All appliances(kWhs)'].sum().unstack()

# Calculate the average monthly consumption across all buildings
monthly_average_consumption = monthly_consumption.mean(axis=1)

# Convert index back to datetime for plotting
monthly_consumption.index = monthly_consumption.index.to_timestamp()

plt.figure(figsize=(7, 4))

for building in buildings:
    plt.plot(monthly_consumption.index, monthly_consumption[building], label=f'Building {building}')
# Add the average consumption line
plt.plot(monthly_consumption.index, monthly_average_consumption, color='black', linestyle='--', linewidth=2, label='Average')

# Set x-axis to display months from December 2021 to May 2022
plt.xticks(monthly_consumption.index, monthly_consumption.index.strftime('%b %Y'), rotation=45)
plt.ylabel('Total energy consumption from All appliances(kWh)')
plt.title('Total Energy Consumption by Month (Dec 2021 - May 2022)')
plt.legend(title='Eve Park',fontsize='7',loc='upper right')
plt.grid(True)
plt.tight_layout()
plt.show()

# Plot Heating load by month, detect anomolies and print them if there are any.

from scipy.stats import zscore

# Filter data for buildings 301 to 312
buildings = [301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312]
df_filtered = df[df['Building number'].isin(buildings)]
# Group by month and building number to calculate monthly heating load
monthly_consumption = df_filtered.groupby([df_filtered['DateTime'].dt.to_period('M'), 'Building number'])['Heating Load (kWhs)'].sum().unstack()

# Calculate the average monthly consumption across all buildings
monthly_average_consumption = monthly_consumption.mean(axis=1)

# Detect anomalies using Z-score for each building and print them if found
for building in buildings:
    # Calculate Z-score for each building’s monthly heating load
    monthly_consumption[f'z_score_{building}'] = zscore(monthly_consumption[building].fillna(0))

    # Identify anomalies (e.g., Z-score threshold of 2)
    building_anomalies = monthly_consumption[(monthly_consumption[f'z_score_{building}'] > 2) |
                                             (monthly_consumption[f'z_score_{building}'] < -2)]
    # Print anomalies if there are any for this building
    if not building_anomalies.empty:
        print(f"Anomalies detected for Building {building}:")
        print(building_anomalies[[building]])
        print("\n")

# Convert index back to datetime for plotting
monthly_consumption.index = monthly_consumption.index.to_timestamp()

plt.figure(figsize=(6, 4))

for building in buildings:
    plt.plot(monthly_consumption.index, monthly_consumption[building], label=f'Building {building}')
# Add the average consumption line
plt.plot(monthly_consumption.index, monthly_average_consumption, color='black', linestyle='--', linewidth=2, label='Average')

# Set x-axis to display months from December 2021 to May 2022
plt.xticks(monthly_consumption.index, monthly_consumption.index.strftime('%b %Y'), rotation=45)
plt.ylabel('Heating Load (kWh)')
plt.title('Monthly Heating Load')
plt.legend(title='Eve Park',fontsize='7',loc='upper left')
plt.grid(True)
plt.tight_layout()
plt.show()

# Print anomalies if there are any for this building
if not building_anomalies.empty:
        print(f"Anomalies detected for Building {building}:")
        print(building_anomalies[[building]])
        print("\n")
else:
    print("No anomalies detected.")

# Plot Cooling load by month

# Group by month and building number to calculate monthly cooling load
monthly_consumption = df_filtered.groupby([df_filtered['DateTime'].dt.to_period('M'), 'Building number'])['Cooling Load (kWhs)'].sum().unstack()

# Calculate the average monthly consumption across all buildings
monthly_average_consumption = monthly_consumption.mean(axis=1)

# Convert index back to datetime for plotting
monthly_consumption.index = monthly_consumption.index.to_timestamp()

plt.figure(figsize=(6, 4))

for building in buildings:
    plt.plot(monthly_consumption.index, monthly_consumption[building], label=f'Building {building}')
# Add the average consumption line
plt.plot(monthly_consumption.index, monthly_average_consumption, color='black', linestyle='--', linewidth=2, label='Average')

# Set x-axis to display months from December 2021 to May 2022
plt.xticks(monthly_consumption.index, monthly_consumption.index.strftime('%b %Y'), rotation=45)
plt.ylabel('Cooling Load (kWh)')
plt.title('Monthly Cooling Load')
plt.legend(title='Eve Park',fontsize='7')
plt.grid(True)
plt.tight_layout()
plt.show()

# Plot Non HVAC load by month

# Group by month and building number to calculate monthly cooling load
monthly_consumption = df_filtered.groupby([df_filtered['DateTime'].dt.to_period('M'), 'Building number'])['Non HVAC (kWh)'].sum().unstack()

# Calculate the average monthly consumption across all buildings
monthly_average_consumption = monthly_consumption.mean(axis=1)

# Convert index back to datetime for plotting
monthly_consumption.index = monthly_consumption.index.to_timestamp()

plt.figure(figsize=(6, 4))

for building in buildings:
    plt.plot(monthly_consumption.index, monthly_consumption[building], label=f'Building {building}')
# Add the average consumption line
plt.plot(monthly_consumption.index, monthly_average_consumption, color='black', linestyle='--', linewidth=2, label='Average')

# Set x-axis to display months from December 2021 to May 2022
plt.xticks(monthly_consumption.index, monthly_consumption.index.strftime('%b %Y'), rotation=45)
plt.ylabel('Non HVAC (kWh)')
plt.title('Monthly Non HVAC Load')
plt.legend(title='Eve Park',fontsize='7')
plt.grid(True)
plt.tight_layout()
plt.show()

#Plot Average loads per day of the week

# Group by day of the week and calculate the average for heating and cooling loads
weekly_avg = df.groupby('day_of_week')[['Heating Load (kWhs)', 'Cooling Load (kWhs)', 'Non HVAC (kWh)']].mean()

plt.figure(figsize=(5, 3))

# Plot average heating load
plt.plot(weekly_avg.index, weekly_avg['Heating Load (kWhs)'], label='Average Heating Load (kWhs)', color='red', marker='o')

# Plot average cooling load
plt.plot(weekly_avg.index, weekly_avg['Cooling Load (kWhs)'], label='Average Cooling Load (kWhs)', color='blue', marker='o')

# Plot average Non HVAC
plt.plot(weekly_avg.index, weekly_avg['Non HVAC (kWh)'], label='Average Non HVAC Load (kWhs)', color='green', marker='o')

# Set x-axis labels to days of the week
plt.xticks(ticks=range(7), labels=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],rotation=45)

plt.xlabel('Day of the Week')
plt.ylabel('Average Load (kWhs)')
plt.title('Average Heating, Cooling, and Non HVAC Loads for Each Day of the Week',fontsize='9')

plt.legend(fontsize='8')
plt.legend(loc='center', bbox_to_anchor=(.5, .3))
plt.grid(True)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Select relevant features and the target variables for correlation analysis
correlation_df = df[['Heating Load (kWhs)', 'Cooling Load (kWhs)', 'Total energy consumption-All appliances(kWhs)', 'Non HVAC (kWh)', 'Non HVAC +1h (kWh)', 'Non HVAC +2h (kWh)',
                     'Air temperature - average (°C)', 'Relative humidity (%)', 'Precipitation (mm)', 'Solar radiation - horizontal (Wh/m²)',
                     'Atmospheric pressure (kPa)', 'Wind speed (m/s)', 'Earth temperature (°C)', 'ω (kg H2O/kg dry air)']]

# Display the first few rows to ensure the data is correct
correlation_df.head()

# Calculate correlation matrix
correlation_matrix = correlation_df.corr()

# Plot heatmap
plt.figure(figsize=(7, 7))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', square=True, fmt=".2f")
plt.title('Correlation Matrix of Weather Features and Heating/Cooling Loads',fontsize=10)
plt.xticks(rotation=45, ha='right')  # Rotate x-axis labels for better readability
plt.yticks(rotation=0)  # Ensure y-axis labels are horizontal
plt.show()

# Encode the 'season' column using LabelEncoder
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['season'] = label_encoder.fit_transform(df['season'])

# Select relevant features for prediction
X = df[['hour', 'day', 'month', 'season', 'day_of_week', 'Air temperature - average (°C)',
        'Relative humidity (%)', 'Wind speed (m/s)', 'Solar radiation - horizontal (Wh/m²)',
        'Total energy consumption-All appliances(kWhs)', 'Non HVAC (kWh)', 'ω (kg H2O/kg dry air)']]

# Target variables (heating and cooling loads)
y_heating = df['Heating Load (kWhs)']
y_cooling = df['Cooling Load (kWhs)']

from sklearn.model_selection import train_test_split

# Split the data into training and test sets
X_train, X_test, y_train_heating, y_test_heating = train_test_split(X, y_heating, test_size=0.2, random_state=42)
X_train, X_test, y_train_cooling, y_test_cooling = train_test_split(X, y_cooling, test_size=0.2, random_state=42)


import xgboost as xgb

# Instantiate an XGBoost model
model_heating = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=100, max_depth=6)
model_cooling = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=100, max_depth=6)

# Train the models on the normalized target
model_heating.fit(X_train, y_train_heating.to_numpy())
model_cooling.fit(X_train, y_train_cooling.to_numpy())

# Make predictions on the test set
# Convert X_test to NumPy array
y_pred_heating = model_heating.predict(X_test.to_numpy())
y_pred_cooling = model_cooling.predict(X_test.to_numpy())

# Evaluate the model
from sklearn.metrics import mean_squared_error, r2_score
mse_heating = mean_squared_error(y_test_heating, y_pred_heating)
r2_heating = r2_score(y_test_heating, y_pred_heating)

mse_cooling = mean_squared_error(y_test_cooling, y_pred_cooling)
r2_cooling = r2_score(y_test_cooling, y_pred_cooling)

print(f'Mean Squared Error (Heating Load): {mse_heating}')
print(f'R^2 Score (Heating Load): {r2_heating}')
print(f'Mean Squared Error (Cooling Load): {mse_cooling}')
print(f'R^2 Score (Cooling Load): {r2_cooling}')

# Actual vs. Predicted Plot for Heating Load
plt.figure(figsize=(6, 6))
plt.scatter(y_test_heating, y_pred_heating, alpha=0.7, color='blue', label='Predictions')
plt.plot([y_test_heating.min(), y_test_heating.max()],
         [y_test_heating.min(), y_test_heating.max()],
         'r--', label='Perfect Prediction')
plt.xlabel("Actual Heating Load (kWh)")
plt.ylabel("Predicted Heating Load (kWh)")
plt.title("Actual vs Predicted Heating Load")
plt.legend()
plt.show()

# Actual vs. Predicted Plot for Cooling Load
plt.figure(figsize=(6, 6))
plt.scatter(y_test_cooling, y_pred_cooling, alpha=0.7, color='green', label='Predictions')
plt.plot([y_test_cooling.min(), y_test_cooling.max()],
         [y_test_cooling.min(), y_test_cooling.max()],
         'r--', label='Perfect Prediction')
plt.xlabel("Actual Cooling Load (kWh)")
plt.ylabel("Predicted Cooling Load (kWh)")
plt.title("Actual vs Predicted Cooling Load")
plt.legend()
plt.show()

# Make prediction on sample input

sample_data = pd.DataFrame({
    'DateTime': ['2/14/2022 2:00:00 PM'],
    'Building number': [302],
    'Air temperature - average (°C)': [-8.63],
    'Relative humidity (%)': [0.5944],
    'Wind speed (m/s)': [4.78],
    'Solar radiation - horizontal (Wh/m²)': [523.17],
    'ω (kg H2O/kg dry air)': [-0.037],
    'Total energy consumption-All appliances(kWhs)': [0.321],
    'Non HVAC (kWh)': [0.0998],
})

# Convert the 'DateTime' column to datetime format
sample_data['DateTime'] = pd.to_datetime(sample_data['DateTime'])

# Extract hour, day, month, and season from the 'DateTime' column
sample_data['hour'] = sample_data['DateTime'].dt.hour
sample_data['day'] = sample_data['DateTime'].dt.day
sample_data['month'] = sample_data['DateTime'].dt.month
sample_data['season'] = sample_data['month'].apply(lambda x: 'Winter' if x in [12, 1, 2, 3] else ('Spring' if x in [4, 5] else 'Other'))

# Extract day of the week (0 = Monday, 6 = Sunday)
sample_data['day_of_week'] = sample_data['DateTime'].dt.dayofweek

# Display the features of the sample data
print(sample_data[['DateTime', 'hour', 'day', 'month', 'season', 'day_of_week']])

# Convert 'season' to categorical type
sample_data['season'] = pd.Categorical(sample_data['season'])

# Use the trained model to predict heating and cooling loads
heating_load_prediction = model_heating.predict(sample_data[['hour', 'day', 'month', 'season', 'day_of_week', 'Air temperature - average (°C)',
                                                             'Relative humidity (%)', 'Wind speed (m/s)', 'Solar radiation - horizontal (Wh/m²)',
                                                             'Total energy consumption-All appliances(kWhs)',
                                                             'Non HVAC (kWh)', 'ω (kg H2O/kg dry air)']])

cooling_load_prediction = model_cooling.predict(sample_data[['hour', 'day', 'month', 'season', 'day_of_week', 'Air temperature - average (°C)',
                                                             'Relative humidity (%)', 'Wind speed (m/s)', 'Solar radiation - horizontal (Wh/m²)',
                                                             'Total energy consumption-All appliances(kWhs)',
                                                             'Non HVAC (kWh)', 'ω (kg H2O/kg dry air)']])

# Display the predictions
print(f"Predicted Heating Load for building 302 on 2/14/2022 at 2:00 PM: {heating_load_prediction[0]} kWh")
print(f"Predicted Cooling Load for building 302 on 2/14/2022 at 2:00 PM: {cooling_load_prediction[0]} kWh")

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# ANN
# Select relevant features for prediction
X = df[['hour', 'day', 'month', 'season', 'day_of_week', 'Air temperature - average (°C)',
        'Relative humidity (%)', 'Wind speed (m/s)', 'Solar radiation - horizontal (Wh/m²)',
        'Total energy consumption-All appliances(kWhs)', 'Non HVAC (kWh)', 'ω (kg H2O/kg dry air)']]

# Target variables (heating and cooling loads)
y_heating = df['Heating Load (kWhs)']
y_cooling = df['Cooling Load (kWhs)']

# One-hot encode categorical variables if present and scale features
X = pd.get_dummies(X, drop_first=True)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split the data into training and test sets
X_train, X_test, y_train_heating, y_test_heating = train_test_split(
    X, y_heating, test_size=0.2, random_state=42)
X_train, X_test, y_train_cooling, y_test_cooling = train_test_split(
    X, y_cooling, test_size=0.2, random_state=42)

# Train on Heating Load
model_heating = Sequential([
    Dense(64, input_dim=X_train.shape[1], activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')
])
model_heating.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error'])
history_heating = model_heating.fit(X_train, y_train_heating, validation_split=0.2, epochs=50, batch_size=32, verbose=0)

# Train on Cooling Load
model_cooling = Sequential([
    Dense(64, input_dim=X_train.shape[1], activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')
])
model_cooling.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error'])
history_cooling = model_cooling.fit(X_train, y_train_cooling, validation_split=0.2, epochs=50, batch_size=32, verbose=0)

# Evaluate the models on test data
heating_loss, heating_mae = model_heating.evaluate(X_test, y_test_heating, verbose=0)
cooling_loss, cooling_mae = model_cooling.evaluate(X_test, y_test_cooling, verbose=0)

from sklearn.metrics import r2_score
# Predict on the test set
y_pred_heating = model_heating.predict(X_test)
y_pred_cooling = model_cooling.predict(X_test)

# Calculate R-squared
r2_heating = r2_score(y_test_heating, y_pred_heating)
r2_cooling = r2_score(y_test_cooling, y_pred_cooling)

print(f"Heating Load - Test Loss: {heating_loss}, Test MAE: {heating_mae}, Heating Load - Test R-square: {r2_heating}")
print(f"Cooling Load - Test Loss: {cooling_loss}, Test MAE: {cooling_mae}, Cooling Load - Test R-square: {r2_cooling}")

import matplotlib.pyplot as plt
import numpy as np

# Plot actual vs. predicted values for Heating Load
plt.figure(figsize=(6, 6))
plt.scatter(y_test_heating, y_pred_heating, alpha=0.7, color='blue', label='Heating Load')
plt.plot([y_test_heating.min(), y_test_heating.max()],
         [y_test_heating.min(), y_test_heating.max()],
         'r--', label='Perfect Prediction')
plt.xlabel("Actual Heating Load (kWh)")
plt.ylabel("Predicted Heating Load (kWh)")
plt.title("Actual vs Predicted Heating Load")
plt.legend()
plt.show()

# Plot actual vs. predicted values for Cooling Load
plt.figure(figsize=(6, 6))
plt.scatter(y_test_cooling, y_pred_cooling, alpha=0.7, color='green', label='Cooling Load')
plt.plot([y_test_cooling.min(), y_test_cooling.max()],
         [y_test_cooling.min(), y_test_cooling.max()],
         'r--', label='Perfect Prediction')
plt.xlabel("Actual Cooling Load (kWh)")
plt.ylabel("Predicted Cooling Load (kWh)")
plt.title("Actual vs Predicted Cooling Load")
plt.legend()
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# ANN without weather data
# Select relevant features for prediction
X = df[['hour', 'day', 'month', 'season', 'day_of_week', 'Total energy consumption-All appliances(kWhs)', 'Non HVAC (kWh)']]

# Target variables (heating and cooling loads)
y_heating = df['Heating Load (kWhs)']
y_cooling = df['Cooling Load (kWhs)']

# One-hot encode categorical variables if present and scale features
X = pd.get_dummies(X, drop_first=True)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split the data into training and test sets
X_train, X_test, y_train_heating, y_test_heating = train_test_split(
    X, y_heating, test_size=0.2, random_state=42)
X_train, X_test, y_train_cooling, y_test_cooling = train_test_split(
    X, y_cooling, test_size=0.2, random_state=42)

# Train on Heating Load
model_heating = Sequential([
    Dense(64, input_dim=X_train.shape[1], activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')
])
model_heating.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error'])
history_heating = model_heating.fit(X_train, y_train_heating, validation_split=0.2, epochs=50, batch_size=32, verbose=0)

# Train on Cooling Load
model_cooling = Sequential([
    Dense(64, input_dim=X_train.shape[1], activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')
])
model_cooling.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error'])
history_cooling = model_cooling.fit(X_train, y_train_cooling, validation_split=0.2, epochs=50, batch_size=32, verbose=0)

# Evaluate the models on test data
heating_loss, heating_mae = model_heating.evaluate(X_test, y_test_heating, verbose=0)
cooling_loss, cooling_mae = model_cooling.evaluate(X_test, y_test_cooling, verbose=0)

from sklearn.metrics import r2_score
# Predict on the test set
y_pred_heating = model_heating.predict(X_test)
y_pred_cooling = model_cooling.predict(X_test)

# Calculate R-squared
r2_heating = r2_score(y_test_heating, y_pred_heating)
r2_cooling = r2_score(y_test_cooling, y_pred_cooling)

print(f"Heating Load - Test Loss: {heating_loss}, Test MAE: {heating_mae}, Heating Load - Test R-square: {r2_heating}")
print(f"Cooling Load - Test Loss: {cooling_loss}, Test MAE: {cooling_mae}, Cooling Load - Test R-square: {r2_cooling}")

import matplotlib.pyplot as plt
import numpy as np

# Plot actual vs. predicted values for Heating Load
plt.figure(figsize=(6, 6))
plt.scatter(y_test_heating, y_pred_heating, alpha=0.7, color='blue', label='Heating Load')
plt.plot([y_test_heating.min(), y_test_heating.max()],
         [y_test_heating.min(), y_test_heating.max()],
         'r--', label='Perfect Prediction')
plt.xlabel("Actual Heating Load (kWh)")
plt.ylabel("Predicted Heating Load (kWh)")
plt.title("Actual vs Predicted Heating Load")
plt.legend()
plt.show()

# Plot actual vs. predicted values for Cooling Load
plt.figure(figsize=(6, 6))
plt.scatter(y_test_cooling, y_pred_cooling, alpha=0.7, color='green', label='Cooling Load')
plt.plot([y_test_cooling.min(), y_test_cooling.max()],
         [y_test_cooling.min(), y_test_cooling.max()],
         'r--', label='Perfect Prediction')
plt.xlabel("Actual Cooling Load (kWh)")
plt.ylabel("Predicted Cooling Load (kWh)")
plt.title("Actual vs Predicted Cooling Load")
plt.legend()
plt.show()

# ANN with only weather
# Select relevant features for prediction
X = df[['hour', 'day', 'month', 'season', 'day_of_week', 'Air temperature - average (°C)',
        'Relative humidity (%)', 'Wind speed (m/s)', 'Solar radiation - horizontal (Wh/m²)',
        'ω (kg H2O/kg dry air)']]

# Target variables (heating and cooling loads)
y_heating = df['Heating Load (kWhs)']
y_cooling = df['Cooling Load (kWhs)']

# One-hot encode categorical variables if present and scale features
X = pd.get_dummies(X, drop_first=True)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split the data into training and test sets
X_train, X_test, y_train_heating, y_test_heating = train_test_split(
    X, y_heating, test_size=0.2, random_state=42)
X_train, X_test, y_train_cooling, y_test_cooling = train_test_split(
    X, y_cooling, test_size=0.2, random_state=42)

# Train on Heating Load
model_heating = Sequential([
    Dense(64, input_dim=X_train.shape[1], activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')
])
model_heating.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error'])
history_heating = model_heating.fit(X_train, y_train_heating, validation_split=0.2, epochs=50, batch_size=32, verbose=0)

# Train on Cooling Load
model_cooling = Sequential([
    Dense(64, input_dim=X_train.shape[1], activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')
])
model_cooling.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error'])
history_cooling = model_cooling.fit(X_train, y_train_cooling, validation_split=0.2, epochs=50, batch_size=32, verbose=0)

# Evaluate the models on test data
heating_loss, heating_mae = model_heating.evaluate(X_test, y_test_heating, verbose=0)
cooling_loss, cooling_mae = model_cooling.evaluate(X_test, y_test_cooling, verbose=0)

from sklearn.metrics import r2_score
# Predict on the test set
y_pred_heating = model_heating.predict(X_test)
y_pred_cooling = model_cooling.predict(X_test)

# Calculate R-squared
r2_heating = r2_score(y_test_heating, y_pred_heating)
r2_cooling = r2_score(y_test_cooling, y_pred_cooling)

print(f"Heating Load - Test Loss: {heating_loss}, Test MAE: {heating_mae}, Heating Load - Test R-square: {r2_heating}")
print(f"Cooling Load - Test Loss: {cooling_loss}, Test MAE: {cooling_mae}, Cooling Load - Test R-square: {r2_cooling}")

import matplotlib.pyplot as plt
import numpy as np

# Plot actual vs. predicted values for Heating Load
plt.figure(figsize=(6, 6))
plt.scatter(y_test_heating, y_pred_heating, alpha=0.7, color='blue', label='Heating Load')
plt.plot([y_test_heating.min(), y_test_heating.max()],
         [y_test_heating.min(), y_test_heating.max()],
         'r--', label='Perfect Prediction')
plt.xlabel("Actual Heating Load (kWh)")
plt.ylabel("Predicted Heating Load (kWh)")
plt.title("Actual vs Predicted Heating Load")
plt.legend()
plt.show()

# Plot actual vs. predicted values for Cooling Load
plt.figure(figsize=(6, 6))
plt.scatter(y_test_cooling, y_pred_cooling, alpha=0.7, color='green', label='Cooling Load')
plt.plot([y_test_cooling.min(), y_test_cooling.max()],
         [y_test_cooling.min(), y_test_cooling.max()],
         'r--', label='Perfect Prediction')
plt.xlabel("Actual Cooling Load (kWh)")
plt.ylabel("Predicted Cooling Load (kWh)")
plt.title("Actual vs Predicted Cooling Load")
plt.legend()
plt.show()

# ANN with total consumption and omega
# Select relevant features for prediction
X = df[['hour', 'day', 'month', 'season', 'day_of_week', 'Total energy consumption-All appliances(kWhs)', 'ω (kg H2O/kg dry air)']]

# Target variables (heating and cooling loads)
y_heating = df['Heating Load (kWhs)']
y_cooling = df['Cooling Load (kWhs)']

# One-hot encode categorical variables if present and scale features
X = pd.get_dummies(X, drop_first=True)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split the data into training and test sets
X_train, X_test, y_train_heating, y_test_heating = train_test_split(
    X, y_heating, test_size=0.2, random_state=42)
X_train, X_test, y_train_cooling, y_test_cooling = train_test_split(
    X, y_cooling, test_size=0.2, random_state=42)

# Train on Heating Load
model_heating = Sequential([
    Dense(64, input_dim=X_train.shape[1], activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')
])
model_heating.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error'])
history_heating = model_heating.fit(X_train, y_train_heating, validation_split=0.2, epochs=50, batch_size=32, verbose=0)

# Train on Cooling Load
model_cooling = Sequential([
    Dense(64, input_dim=X_train.shape[1], activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')
])
model_cooling.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error'])
history_cooling = model_cooling.fit(X_train, y_train_cooling, validation_split=0.2, epochs=50, batch_size=32, verbose=0)

# Evaluate the models on test data
heating_loss, heating_mae = model_heating.evaluate(X_test, y_test_heating, verbose=0)
cooling_loss, cooling_mae = model_cooling.evaluate(X_test, y_test_cooling, verbose=0)

from sklearn.metrics import r2_score
# Predict on the test set
y_pred_heating = model_heating.predict(X_test)
y_pred_cooling = model_cooling.predict(X_test)

# Calculate R-squared
r2_heating = r2_score(y_test_heating, y_pred_heating)
r2_cooling = r2_score(y_test_cooling, y_pred_cooling)

print(f"Heating Load - Test Loss: {heating_loss}, Test MAE: {heating_mae}, Heating Load - Test R-square: {r2_heating}")
print(f"Cooling Load - Test Loss: {cooling_loss}, Test MAE: {cooling_mae}, Cooling Load - Test R-square: {r2_cooling}")

import matplotlib.pyplot as plt
import numpy as np

# Plot actual vs. predicted values for Heating Load
plt.figure(figsize=(6, 6))
plt.scatter(y_test_heating, y_pred_heating, alpha=0.7, color='blue', label='Heating Load')
plt.plot([y_test_heating.min(), y_test_heating.max()],
         [y_test_heating.min(), y_test_heating.max()],
         'r--', label='Perfect Prediction')
plt.xlabel("Actual Heating Load (kWh)")
plt.ylabel("Predicted Heating Load (kWh)")
plt.title("Actual vs Predicted Heating Load")
plt.legend()
plt.show()

# Plot actual vs. predicted values for Cooling Load
plt.figure(figsize=(6, 6))
plt.scatter(y_test_cooling, y_pred_cooling, alpha=0.7, color='green', label='Cooling Load')
plt.plot([y_test_cooling.min(), y_test_cooling.max()],
         [y_test_cooling.min(), y_test_cooling.max()],
         'r--', label='Perfect Prediction')
plt.xlabel("Actual Cooling Load (kWh)")
plt.ylabel("Predicted Cooling Load (kWh)")
plt.title("Actual vs Predicted Cooling Load")
plt.legend()
plt.show()